version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: sera-tutorial-rabbitmq
    #    restart: unless-stopped
    #    build:
    #      context: ./docker/rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
      - "15675:15675"
      - "1885:1885"
    #    command: "/bin/bash -c \"rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_amqp1_0; rabbitmq-server\""
    #
    volumes:
      #      - ./docker-data/rabbitmq/config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      #      - ./docker-data/rabbitmq/config/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./docker-data/rabbitmq/config:/etc/rabbitmq:ro
      - ./docker-data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker-data/rabbitmq/logs/:/var/log/rabbitmq/
    #      - /data/docker/rabbitmq/config:/etc/rabbitmq:ro
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "rabbitpassword"
#    env_file:
#      - ./docker-data/rabbitmq/config/login.env
#    volumes:
#      - type: bind
#        source: ./docker-data/rabbitmq/config/rabbitmq.conf
#        target: /etc/rabbitmq/rabbitmq.conf
#        read_only: true

networks:
  backend: