#spring.application.name=service
spring:
  application:
    name: service
#  modulith:
#    events:
#      externalization:
#        enabled: true


  #  modulith:
##    republish-outstanding-events-on-restart: true
##    moments:
##      granularity: hours
##      enable-time-machine: true
#    events:



  docker.docker.compose.lifecycle-management: start_only

  sql.init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/mydatabase
    username: myuser
    password: secret
  jpa:
    database: postgresql
    ddl-auto: update
    use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.modulith: debug

