#spring.application.name=service
spring:
  application:
    name: service

  modulith:
    moments:
      granularity: hours
      enable-time-machine: true
    events:
      jdbc:
        schema-initialization:
          enabled: true

  docker.docker.compose.lifecycle-management: start_only

  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost/mydatabase
    username: myuser
    password: secret
##
#
#
#spring.modulith.events.jdbc.schema-initialization.enabled=true
#spring.modulith.moments.enable-time-machine=true
#spring.modulith.moments.granularity=hours
##
#spring.docker.compose.lifecycle-management=start_only
##
#spring.sql.init.mode=always
#spring.datasource.url=jdbc:postgresql://localhost/mydatabase
#spring.datasource.username=myuser
#spring.datasource.password=secret
##
#spring.rabbitmq.username=myuser
#spring.rabbitmq.password=secret
##
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#
##
#spring.threads.virtual.enabled=true