#spring:
#  config:
#    activate:
#      on-profile: test
#  datasource:
#    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
##    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 1234
#    url: jdbc:tc:mysql://localhost:3306/sera-tutorial?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
#    username: sera-tutorial
#    jpa:
#      database: mysql
#      hibernate:
#        ddl-auto: create
#      properties:
#        hibernate:
#          format_sql: true
#      show-sql: true

spring:
  datasource:
    url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS HELLO\;CREATE SCHEMA IF NOT EXISTS WORLD
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create